//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceMonitoringSystem.hospitalResourcetest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://hospitalresource.ws.nmmps.dhcc.com/", ConfigurationName="hospitalResourcetest.HospitalResourceWServiceInterface")]
    public interface HospitalResourceWServiceInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="receiveResourceData", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string receiveResourceData(string requestData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HospitalResourceWServiceInterfaceChannel : PriceMonitoringSystem.hospitalResourcetest.HospitalResourceWServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HospitalResourceWServiceInterfaceClient : System.ServiceModel.ClientBase<PriceMonitoringSystem.hospitalResourcetest.HospitalResourceWServiceInterface>, PriceMonitoringSystem.hospitalResourcetest.HospitalResourceWServiceInterface {
        
        public HospitalResourceWServiceInterfaceClient() {
        }
        
        public HospitalResourceWServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HospitalResourceWServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HospitalResourceWServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HospitalResourceWServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string receiveResourceData(string requestData) {
            return base.Channel.receiveResourceData(requestData);
        }
    }
}
