//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceMonitoringSystem.materialPriceTracetest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://materialpricetrace.ws.nmmps.dhcc.com/", ConfigurationName="materialPriceTracetest.MaterialPriceTraceWServiceInterface")]
    public interface MaterialPriceTraceWServiceInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="receiveMaterialPriceData", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string receiveMaterialPriceData(string requestData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MaterialPriceTraceWServiceInterfaceChannel : PriceMonitoringSystem.materialPriceTracetest.MaterialPriceTraceWServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaterialPriceTraceWServiceInterfaceClient : System.ServiceModel.ClientBase<PriceMonitoringSystem.materialPriceTracetest.MaterialPriceTraceWServiceInterface>, PriceMonitoringSystem.materialPriceTracetest.MaterialPriceTraceWServiceInterface {
        
        public MaterialPriceTraceWServiceInterfaceClient() {
        }
        
        public MaterialPriceTraceWServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaterialPriceTraceWServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialPriceTraceWServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialPriceTraceWServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string receiveMaterialPriceData(string requestData) {
            return base.Channel.receiveMaterialPriceData(requestData);
        }
    }
}
