//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceMonitoringSystem.drugPriceTracetest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://drugpricetrace.ws.nmmps.dhcc.com/", ConfigurationName="drugPriceTracetest.DrugPriceTraceWServiceInterface")]
    public interface DrugPriceTraceWServiceInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="receiveDrugData", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string receiveDrugData(string requestData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DrugPriceTraceWServiceInterfaceChannel : PriceMonitoringSystem.drugPriceTracetest.DrugPriceTraceWServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DrugPriceTraceWServiceInterfaceClient : System.ServiceModel.ClientBase<PriceMonitoringSystem.drugPriceTracetest.DrugPriceTraceWServiceInterface>, PriceMonitoringSystem.drugPriceTracetest.DrugPriceTraceWServiceInterface {
        
        public DrugPriceTraceWServiceInterfaceClient() {
        }
        
        public DrugPriceTraceWServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DrugPriceTraceWServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DrugPriceTraceWServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DrugPriceTraceWServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string receiveDrugData(string requestData) {
            return base.Channel.receiveDrugData(requestData);
        }
    }
}
