//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceMonitoringSystem.servicePriceTracetest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicepricetrace.ws.nmmps.dhcc.com/", ConfigurationName="servicePriceTracetest.ServicePriceTraceWServiceInterface")]
    public interface ServicePriceTraceWServiceInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="receiveServiceData", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string receiveServiceData(string requestData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicePriceTraceWServiceInterfaceChannel : PriceMonitoringSystem.servicePriceTracetest.ServicePriceTraceWServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePriceTraceWServiceInterfaceClient : System.ServiceModel.ClientBase<PriceMonitoringSystem.servicePriceTracetest.ServicePriceTraceWServiceInterface>, PriceMonitoringSystem.servicePriceTracetest.ServicePriceTraceWServiceInterface {
        
        public ServicePriceTraceWServiceInterfaceClient() {
        }
        
        public ServicePriceTraceWServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePriceTraceWServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePriceTraceWServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePriceTraceWServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string receiveServiceData(string requestData) {
            return base.Channel.receiveServiceData(requestData);
        }
    }
}
