//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceMonitoringSystem.BASYtest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://medicaltemp.ws.drgs.dhcc.com/", ConfigurationName="BASYtest.MedicalTempWServiceInterface")]
    public interface MedicalTempWServiceInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="collection", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string collection(string specType, string orgCode, string fileName, byte[] fileIoByte);
        
        [System.ServiceModel.OperationContractAttribute(Action="xmlcolletion", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string xmlcolletion(string specType, string orgCode, string xmlStr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MedicalTempWServiceInterfaceChannel : PriceMonitoringSystem.BASYtest.MedicalTempWServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MedicalTempWServiceInterfaceClient : System.ServiceModel.ClientBase<PriceMonitoringSystem.BASYtest.MedicalTempWServiceInterface>, PriceMonitoringSystem.BASYtest.MedicalTempWServiceInterface {
        
        public MedicalTempWServiceInterfaceClient() {
        }
        
        public MedicalTempWServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MedicalTempWServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MedicalTempWServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MedicalTempWServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string collection(string specType, string orgCode, string fileName, byte[] fileIoByte) {
            return base.Channel.collection(specType, orgCode, fileName, fileIoByte);
        }
        
        public string xmlcolletion(string specType, string orgCode, string xmlStr) {
            return base.Channel.xmlcolletion(specType, orgCode, xmlStr);
        }
    }
}
